packages:
  - layer
  - docs

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true

minimumReleaseAge: 0

allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: true
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false

overrides:
  'nuxt': 4.4.6
