name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build -t movk-nuxt-docs:latest .

      - name: Deploy
        run: |
          cd ~/deploy
          docker compose up -d movk-nuxt-docs
          docker image prune -f
